import sys

sys.path.append("/www/alpha/")

from pydantic import BaseModel

from apps.rubicon_v3.__function.__utils import get_prompt_from_obj
from apps.rubicon_v3.__function.__llm_call import open_ai_call_structured
from apps.rubicon_v3.__function.definitions import response_types


class QueryExpansion(BaseModel):
    expanded_query: str


def query_expansion(
    main_query: str,
    language: str,
    country_code: str,
    model_name: str = "gpt-4.1-mini",
):
    """
    Query expansion function to enhance the user's search query.

    Args:
        main_query (str): The original search query provided by the user.
        language (str): The language in which the query is to be processed.
        country_code (str): The country code for localization purposes.
        model_name (str): The name of the OpenAI model to use for query expansion.

    Returns:
        str: The expanded search query generated by the model.
    """
    # Get the prompt from db
    prompt = get_prompt_from_obj(
        category_lv1="query_expansion_search_summary",
        country_code=country_code,
        response_type=response_types.QUERY_EXPANSION,
    )
    prompt = prompt.replace("{output_language}", language)

    # Initialize the messages for the OpenAI API call
    messages = [{"role": "system", "content": prompt}]
    user_content = [{"type": "text", "text": main_query}]
    messages.append({"role": "user", "content": user_content})

    response = open_ai_call_structured(
        model_name, messages, QueryExpansion, 0.01, 0.1, 42
    )

    return response.get("expanded_query")
