# Generated by Django 5.1.1 on 2024-10-29 13:00

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha_Function_Repository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20, verbose_name='Category')),
                ('redis_key', models.CharField(max_length=50, verbose_name='Redis Key')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Code')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
            ],
            options={
                'verbose_name_plural': '6. Function Repository',
            },
        ),
        migrations.CreateModel(
            name='Alpha_Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Menu UUID')),
                ('parent_menu_id', models.UUIDField(blank=True, null=True, verbose_name='Parent Menu UUID')),
                ('level', models.IntegerField(verbose_name='Menu Level')),
                ('name', models.CharField(max_length=50, verbose_name='Menu Name')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Name')),
                ('group', models.BooleanField(default=False, verbose_name='Group')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
            options={
                'verbose_name_plural': '1. Menu',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alpha_Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Table Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
            options={
                'verbose_name_plural': '2. Table',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alpha_API',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='API ID')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('request_example', models.JSONField(blank=True, null=True, verbose_name='Request Example')),
                ('response_example', models.JSONField(blank=True, null=True, verbose_name='Response Example')),
                ('no_authentication', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False, verbose_name='No Authentication')),
                ('no_access_control', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False, verbose_name='No Access Control')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
            options={
                'verbose_name_plural': '4. API Docs (Collected by __script/_API_Info_Collector)',
                'unique_together': {('url', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Alpha_Table_Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_seq', models.IntegerField(default=100)),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Field Name')),
                ('hide', models.BooleanField(default=False, verbose_name='Hide Field')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Label')),
                ('align', models.CharField(blank=True, choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], default='center', max_length=10, null=True, verbose_name='Align')),
                ('width', models.CharField(blank=True, default='10%', max_length=10, null=True, verbose_name='Width')),
                ('sortable', models.BooleanField(blank=True, default=False, null=True, verbose_name='Sortable')),
                ('style_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='Class')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha_base.alpha_table', verbose_name='Object')),
            ],
            options={
                'verbose_name_plural': '3. Table Field',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alpha_API_Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='API Parameter ID')),
                ('seq', models.IntegerField(default=10)),
                ('parameter', models.CharField(max_length=20, verbose_name='Parameter')),
                ('required', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False, verbose_name='Required')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('alpha_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alpha_base.alpha_api', verbose_name='Alpha API')),
            ],
            options={
                'verbose_name_plural': '5. API Docs Parameters',
                'unique_together': {('alpha_api', 'parameter')},
            },
        ),
    ]
