# Generated by Django 5.1.1 on 2024-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpha_menu',
            name='service_page_title',
            field=models.JSONField(blank=True, null=True, verbose_name='Service Page Title'),
        ),
        migrations.AddField(
            model_name='alpha_menu',
            name='service_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service URL'),
        ),
    ]
