# Generated by Django 5.1.1 on 2024-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_base', '0002_alpha_menu_service_page_title_alpha_menu_service_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alpha_menu',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='alpha_menu',
            name='service_page_title',
        ),
        migrations.RemoveField(
            model_name='alpha_menu',
            name='service_url',
        ),
        migrations.AddField(
            model_name='alpha_menu',
            name='page_title',
            field=models.JSONField(blank=True, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='alpha_menu',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
