# Generated by Django 5.1.1 on 2024-10-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_base', '0003_remove_alpha_menu_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpha_menu',
            name='icon',
            field=models.CharField(default='-', max_length=30, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
