# Generated by Django 5.1.1 on 2024-10-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_base', '0004_alpha_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpha_menu',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Icon'),
        ),
    ]
