# Generated by Django 5.1.1 on 2024-12-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_base', '0005_alter_alpha_menu_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alpha_menu',
            name='parent_menu_id',
        ),
        migrations.AddField(
            model_name='alpha_menu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_menus', to='alpha_base.alpha_menu'),
        ),
    ]
