import os

# import sys
from datetime import timedelta

"""
Django settings for alpha project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""


import uuid
from pathlib import Path


SITE_ID = 1
##### Environment Settings ##################################
INSTANCE_ID = str(uuid.uuid4()).split("-", maxsplit=1)[0]
RUN_APSCHEDULER = True

LOCATION = os.environ.get("VITE_LOCATION")
VITE_OP_TYPE = os.environ.get("VITE_OP_TYPE")
VITE_COUNTRY = os.environ.get("VITE_COUNTRY")
VITE_API_SERVER_URL = os.environ.get("VITE_API_SERVER_URL")
FRONTEND_DEV_URL = os.environ.get("FRONTEND_DEV_URL")
API_URL_PREFIX = os.environ.get("VITE_PUBLIC_PATH")[1:]
BASE_URL = VITE_API_SERVER_URL + "/" + API_URL_PREFIX

# RQ_QUEUE_NAME          = os.environ.get('RQ_QUEUE_NAME')

POSTGRESQL_IP = os.environ.get("POSTGRESQL_IP")
POSTGRESQL_DB = os.environ.get("POSTGRESQL_DB")
POSTGRESQL_PORT = os.environ.get("POSTGRESQL_PORT")
POSTGRESQL_ID = os.environ.get("POSTGRESQL_ID")
POSTGRESQL_PWD = os.environ.get("POSTGRESQL_PWD")

CLICKHOUSE_HOST = os.environ.get("CLICKHOUSE_HOST")

REDIS_CACHE_IP = os.environ.get("REDIS_CACHE_IP")
REDIS_MAIN_IP = os.environ.get("REDIS_MAIN_IP")
REDIS_TIMEOUT = 300

REDIS_ORCHESTRATOR_IP = os.environ.get("REDIS_MAIN_IP")
REDIS_PORT = 6380
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")
REDIS_ORCHESTRATOR_DB = 7
REDIS_ORCHESTRATOR_TIMEOUT = 60

SERVICE_HEALTH_CHECK_URL = os.environ.get("SERVICE_HEALTH_CHECK_URL")

AZURE_SEARCH_ENDPOINT = os.environ.get("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_API_KEY = os.environ.get("AZURE_SEARCH_API_KEY")
AZURE_SEARCH_API_VERSION = os.environ.get("AZURE_SEARCH_API_VERSION")

EMBEDDING_IP = os.environ.get("EMBEDDING_IP")

GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
SEARCH_ENGINE_ID = os.environ.get("SEARCH_ENGINE_ID")

VITE_ENCRYPTION_KEY = os.environ.get("VITE_ENCRYPTION_KEY")


def override_azure_search_env(country_code):
    if VITE_OP_TYPE == "DEV" and country_code != "KR":
        global AZURE_SEARCH_ENDPOINT, AZURE_SEARCH_API_KEY
        AZURE_SEARCH_ENDPOINT = os.environ.get("AZURE_DEV_GB_SEARCH_ENDPOINT")
        AZURE_SEARCH_API_KEY = os.environ.get("AZURE_DEV_GB_SEARCH_API_KEY")


############################################################

REDIS_MESSAGE_TIMEOUT = 5 * 60

GRPC_SERVER = {"embedding_gpu": [EMBEDDING_IP, "50051"]}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")

ALPHA_API_KEY = os.environ.get("ALPHA_API_KEY")
TAG_INTERFACE_API_KEY = os.environ.get("TAG_INTERFACE_API_KEY")

CSRF_TRUSTED_ORIGINS = [FRONTEND_DEV_URL, VITE_API_SERVER_URL]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("JWT_SECRET_KEY")

AZURE_OPENAI_API_VERSION = "2025-01-01-preview"
AZURE_OPENAI_API_VERSION_20240801 = "2024-08-01-preview"
AZURE_OPENAI_API_ENDPOINT = os.environ.get("AZURE_OPENAI_API_ENDPOINT")
AZURE_OPENAI_API_KEY = os.environ.get("AZURE_OPENAI_API_KEY")

AZURE_OPENAI_API_KEY_KR = os.environ.get("AZURE_OPENAI_API_KEY_KR")
AZURE_OPENAI_API_KEY_UK = os.environ.get("AZURE_OPENAI_API_KEY_UK")
AZURE_OPENAI_API_ENDPOINT_KR = os.environ.get("AZURE_OPENAI_ENDPOINT_KR")
AZURE_OPENAI_API_ENDPOINT_UK = os.environ.get("AZURE_OPENAI_ENDPOINT_UK")

AZURE_OPENAI_EMBEDDING_API_VERSION = "2024-08-01-preview"
AZURE_OPENAI_EMBEDDING_API_ENDPOINT = os.environ.get(
    "AZURE_OPENAI_EMBEDDING_API_ENDPOINT"
)
AZURE_OPENAI_EMBEDDING_API_KEY = os.environ.get("AZURE_OPENAI_EMBEDDING_API_KEY")

AZURE_EMAIL_ENDPOINT = os.getenv("AZURE_EMAIL_ENDPOINT")
AZURE_EMAIL_API_KEY = os.getenv("AZURE_EMAIL_API_KEY")
AZURE_EMAIL_RECIPIENTS = ["suyeon.sung@samsung.com", "jihejihe.kim@samsung.com"]
AZURE_EMAIL_JAEIL_RECIPIENTS = ["mos.baek@samsung.com"]
AZURE_EMAIL_DEVCRA_RECIPIENTS = ["sjj@devcra.com"]
AZURE_EMAIL_CSBOT_RECIPIENTS = [
    "kyungjoon.ko@samsung.com",
    "hyojin4u@samsung.com",
    "jiyoon.myung@samsung.com",
    "choelwoodlcjfdn.lee@samsung.com",
    "suho48.park@samsung.com",
]
AZURE_EMAIL_SPRINKLR_RECIPIENTS = ["samsung.ms.epromoter@sprinklr.com"]
AZURE_EMAIL_DOTCOMSEARCH_RECIPIENTS = [
    "n.mkumaran@samsung.com",
    "ankit2.singh@samsung.com",
    "j.kainth@samsung.com",
    "vijay.bneni@samsung.com",
    "n.mouhammed@partner.samsung.com",
    "karthik.k@samsung.com",
]


# SECURITY WARNING: don't run with debug turned on in production!
# If you need detailed log, set DEBUG to True
if VITE_OP_TYPE in ["PROD", "STG"]:
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ["*"]


# Serializer configurations


# Application definition
INSTALLED_APPS = [
    "jet",
    "daphne",
    "adrf",
    "corsheaders",
    "channels",
    "django_json_widget",
    "django_extensions",
    "model_clone",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.postgres",
    "django_apscheduler",
    "rest_framework",
    "rest_framework_api_key",
    "django_filters",
    "django_rq",
    "apps.__apscheduler",
    "apps.alpha_base",
    "apps.alpha_auth",
    "apps.alpha_log",
    "apps.alpha_test",
    "apps.alpha_example",
    "apps.rubicon_v3",
    "apps.rubicon_admin",
    "apps.rubicon_data",
]

AUTH_USER_MODEL = "alpha_auth.Alpha_User"
AUTH_GROUP_MODEL = "alpha_auth.Alpha_Group"
AUTH_PERMISSION_MODEL = "alpha_auth.Alpha_Permission"
CONTENT_TYPE_MODEL = "alpha_auth.Alpha_Content_Type"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS_ALLOW_HEADERS = "*"
# CORS_ORIGIN_WHITELIST = (
#     "http://localhost:8080",
# )

# CORS_ORIGIN_WHITELIST = ("http://10.156.39.10",)
ROOT_URLCONF = "alpha.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(FRONTEND_DIR, "dist")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = 'alpha.wsgi.application'
ASGI_APPLICATION = "alpha.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


DATABASES = {
    "default": {
        # 'ENGINE': 'django.contrib.gis.db.backends.postgis',
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRESQL_DB,
        "USER": POSTGRESQL_ID,
        "PASSWORD": POSTGRESQL_PWD,
        "HOST": POSTGRESQL_IP,
        "PORT": POSTGRESQL_PORT,
        # 'ENGINE':
        # 'OPTIONS': {
        #     'CONN_MAX_AGE': '60',
        # }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = "en-us"

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Seoul"

USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#############################################################
#############################################################
#############################################################
#############################################################


JSON_EDITOR_JS = "/" + API_URL_PREFIX + "static/js/jsoneditor.js"
JSON_EDITOR_CSS = "/" + API_URL_PREFIX + "static/css/jsoneditor.css"
JSON_EDITOR_INIT_JS = "/" + API_URL_PREFIX + "static/js/jsoneditor-init.js"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

MEDIA_URL = "/" + API_URL_PREFIX + "media/"
STATIC_URL = "/" + API_URL_PREFIX + "static/"

STATICFILES_DIRS = [
    "/www/alpha/static_base/",
    os.path.abspath(os.path.join(FRONTEND_DIR, "dist")),
]

STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, "static"))
MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, "media"))

# redis_client = redis.StrictRedis(
#         host=REDIS_ORCHESTRATOR_IP,
#         port=REDIS_PORT,
#         db=0,
#         password=REDIS_PASSWORD,
#         ssl=True,
#         decode_responses=True)


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"rediss://:{REDIS_PASSWORD}@{REDIS_ORCHESTRATOR_IP}:{REDIS_PORT}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 'PASSWORD': REDIS_PASSWORD,
            "PICKLE_VERSION": -1,  # Will use highest protocol version available
            "SSL": True,
        },
    }
    # 'default': {
    #     'BACKEND': 'django_redis.cache.RedisCache',
    #     'LOCATION': 'redis://127.0.0.1:6379/0',
    #     'OPTIONS': {
    #         'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #     }
    # }
    # 'main': {
    #     'BACKEND': 'django_redis.cache.RedisCache',
    #     'LOCATION': 'redis://{}:6379/0'.format(REDIS_MAIN_IP),
    #     'OPTIONS': {
    #         'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #     }
    # }
}

RQ_MAX_TIMEOUT = 20

RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "DEFAULT_TIMEOUT": RQ_MAX_TIMEOUT,
    },
    "high": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 1,
        "DEFAULT_TIMEOUT": RQ_MAX_TIMEOUT,
    },
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # 'rest_framework.authentication.BasicAuthentication'
    ),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    # 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',)
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # 'user_chatbot': '60/minute',
        # 'anon_chatbot': '50/minute',
        # 'user_id_throttle': '3/minute',
        # 'session_id_throttle': '4/minute',
        "non_multi_user_id_throttle": "30/minute",
        "non_multi_session_id_throttle": "50/minute",
        "multi_user_id_throttle": "100/minute",
        "multi_session_id_throttle": "150/minute",
    },
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}


class bcolors:
    HEADER = "\033[95m"
    BLUE = "\033[94m"
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    RED = "\033[91m"
    WARNING = "\033[93m"
    FAIL = "\033[95m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"


CODEMIRROR_CONFIG = {
    "lineNumbers": True,
}

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
