# Generated by Django 5.1.1 on 2025-01-13 20:56

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha_Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Table Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
            options={
                'verbose_name_plural': '2. Table',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alpha_Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Menu UUID')),
                ('level', models.IntegerField(verbose_name='Menu Level')),
                ('name', models.CharField(max_length=50, verbose_name='Menu Name')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Icon')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('page_title', models.JSONField(blank=True, null=True, verbose_name='Page Title')),
                ('group', models.BooleanField(default=False, verbose_name='Group')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_menus', to='alpha_base.alpha_menu')),
            ],
            options={
                'verbose_name_plural': '1. Menu',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Alpha_Table_Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_seq', models.IntegerField(default=100)),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Field Name')),
                ('hide', models.BooleanField(default=False, verbose_name='Hide Field')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Label')),
                ('align', models.CharField(blank=True, choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], default='center', max_length=10, null=True, verbose_name='Align')),
                ('width', models.CharField(blank=True, default='10%', max_length=10, null=True, verbose_name='Width')),
                ('sortable', models.BooleanField(blank=True, default=False, null=True, verbose_name='Sortable')),
                ('style_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='Class')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha_base.alpha_table', verbose_name='Object')),
            ],
            options={
                'verbose_name_plural': '3. Table Field',
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
